// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActivityProfileMenu: typeof import('./src/components/ActivityProfileMenu.vue')['default']
    BreadCrumbs: typeof import('./src/components/BreadCrumbs.vue')['default']
    CardFood: typeof import('./src/components/CardFood.vue')['default']
    CategoryCousinFood: typeof import('./src/components/CategoryCousinFood.vue')['default']
    CategoryMenuFilter: typeof import('./src/components/CategoryMenuFilter.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    RestaurantTabs: typeof import('./src/components/RestaurantTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCategories: typeof import('./src/components/SectionCategories.vue')['default']
    SectionParts: typeof import('./src/components/SectionParts.vue')['default']
  }
}

export {}
